### ISSUE TITLE
how to run this project?

### ISSUE THREAD

**Issue by vikrant10** [AshlinK/Ecommerce-Django#1]
Hi AshlinK, 
Can you please tell us stepwise, how to run this project in windows.

Thanks

**Comment by AshlinK** [comment]
Hi Vikrant ,

Sure.Follow the below steps.

First you need to make sure you have python installed.
1.  Create a new directory.

2.Do a git clone for this project.

3. Create a virtual environment.
pip install virtualenv 
virtualenv venv

4. Run the requirements.txt file as follows,
pip install -r requirements.txt

5. Once all the modules are installed. Run webserver inside the directory which has manage.py file.

python manage.py runserver

6. The above command will run a local webserver on port 8000. Open your browser and type
localhost:8000


Thanks
Ashlin
