### ISSUE TITLE
No module named 'crm.secrets'

### ISSUE THREAD

**Issue by vikrant10** [AshlinK/Ecommerce-Django#2]
Hi AshlinK,

I followed your steps. But after running `python manage.py runserver`  i am getting `ModuleNotFoundError: No module named 'crm.secrets'`

Could you please look into it and help me here?
Thanks

![Capture](https://user-images.githubusercontent.com/32262306/86793224-dfbcd080-c088-11ea-81ef-ad6d9e4e5c5f.PNG)

**Comment by vikrant10** [comment]
Well, my python version is 3.8

**Comment by AshlinK** [comment]
Create a secrets.py file in the same directory as settings.py. Add the below line,
KEY="YourRandomKey"

**Comment by AshlinK** [comment]
Go through the steps mentioned in the README.md
